// Generated by CoffeeScript 1.7.1
(function() {
  var IS, chai, obj;

  IS = require("../../lib/isf.js");

  chai = require("chai");

  obj = IS.Object.clone();

  chai.should();

  describe("Function Overwrite Module", function() {});

}).call(this);
